version: "3.1"

services:
  db:
    image: postgres:14
    container_name: wikihunt_db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: wikihunt_db
      POSTGRES_USER: wikihunt
      POSTGRES_PASSWORD: wikihunt

    volumes:
      - wikihunt-data:/var/lib/postgresql/data

volumes:
  wikihunt-data:
